package fss.model;

public enum FIFAMeetImportance {
    FRIENDLY_OUT,
    FRIENDLY_IN,
    NATION_LEAGUE_GROUP,
    NATION_LEAGUE_PLAYOFF,
    QUALIFYING,
    CONFEDERATION_UNDER14,
    CONFEDERATION_BEGINFROM14,
    WORLD_UNDER14,
    WORLD_BEGINFROM14
}
