package fss.model;

public enum StageID {
    //Eurocups
    LEAGUE_CHAMPIONS_FISRT_QUAL,
    LEAGUE_CHAMPIONS_SECOND_QUAL,
    LEAGUE_CHAMPIONS_THIRD_QUAL,
    LEAGUE_CHAMPIONS_GROUPS,
    LEAGUE_CHAMPIONS_18,
    LEAGUE_CHAMPIONS_14,
    LEAGUE_CHAMPIONS_12,
    LEAGUE_CHAMPIONS_FINAL,
    EUROPA_LEAGUE_FISRT_QUAL,
    EUROPA_LEAGUE_SECOND_QUAL,
    EUROPA_LEAGUE_THIRD_QUAL,
    EUROPA_LEAGUE_FOURTH_QUAL,
    EUROPA_LEAGUE_GROUP,
    EUROPA_LEAGUE_116,
    EUROPA_LEAGUE_18,
    EUROPA_LEAGUE_14,
    EUROPA_LEAGUE_12,
    EUROPA_LEAGUE_FINAL,
    CONFERENCE_LEAGUE_FISRT_QUAL,
    CONFERENCE_LEAGUE_SECOND_QUAL,
    CONFERENCE_LEAGUE_THIRD_QUAL,
    CONFERENCE_LEAGUE_GROUP,
    CONFERENCE_LEAGUE_116,
    CONFERENCE_LEAGUE_18,
    CONFERENCE_LEAGUE_14,
    CONFERENCE_LEAGUE_12,
    CONFERENCE_LEAGUE_FINAL,


}
